services:
  api:
    build:
      context: .
      dockerfile: src/LoopMeet.Api/Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:${API_PORT:-5001}
    volumes:
      - ~/.microsoft/usersecrets/${API_ID:?Project ID is required}/secrets.json:/root/.microsoft/usersecrets/${API_ID}/secrets.json:ro
